import { spawn } from 'child_process';
import { DateFormat } from './formatDate';
import { GitCommitHandler } from './gitCommitHandler';
import { GitBranch, NWABAPResult } from './Apptypes';
import { readJson, readFileSync, ensureFile, writeJson } from 'fs-extra';
import { parse } from 'yaml';

export class DeployLogger {
  // /**
  //  * Tag the commit with the current timestamp
  //  */
  // const gitTagWithTimeStamp = () => {
  //     return new Promise((resolve, reject) => {
  //         const sTag = formatDate(new Date());
  //         const sMsg = `-m "tag ${sTag} generated by tools-gittag"`;
  //         const child = spawn('git', ['tag', sTag, '-a', sMsg])
  //         child.on('exit', (code) => {
  //             //console.log("git diff-files exited with: " + code);
  //             resolve(code);
  //         })
  //         child.stdout.on('data', (data) => {
  //             console.log(``);
  //         })
  //         child.stderr.on('data', (data) => {
  //             console.error(`stderr: ${data}`);
  //             reject(data.toString());
  //         });
  //     })
  // }

  private async getGitBranch(): Promise<string> {
    return new Promise((resolve, reject) => {
      let result = '';
      const child = spawn('git', ['branch', '--show-current']);
      /* eslint-disable */
      child.on('exit', (code) => {
        // console.log("git branch exited with: " + code);
        // console.log(`result: ${result}`)
        resolve(result);
      })
      child.stdout.on('data', (data) => {
        // console.log(`stdout: ${data}`)
        /* eslint-disable */
        result = data.toString().replace('\n', '');
      })
      child.stderr.on('data', (data) => {
        console.error(`stderr: ${data}`);
        /* eslint-disable */
        reject({ reason: data.toString() });
      });
    })
  }

  private async getGitUser(): Promise<string> {
    return new Promise((resolve, reject) => {
      let result = '';
      const child = spawn('git', ['config', 'user.name']);
      child.on('exit', (code) => {
        // console.log("git config user.name exited with: " + code);
        // console.log(`result: ${result}`)
        resolve(result);
      })
      child.stdout.on('data', (data) => {
        // console.log(`stdout: ${data}`)
        result = data.toString().replace('\n', '');
      })
      child.stderr.on('data', (data) => {
        console.error(`stderr: ${data}`);
        reject(data.toString());
      });
    })
  }

  /*
   * get branch and username from git
   */
  private async getGitParams(): Promise<GitBranch> {
    const result = <GitBranch>{}
    result.branch = await this.getGitBranch()
    result.username = await this.getGitUser()
    return result
  }

  /**
   * gets the package name and version from package.json file 
   * returns {name: string, version: string}
   */
  private async getPackageInfo() {
    const packageJson = await readJson('package.json')
    return { name: packageJson.name, version: packageJson.version }
  }

  private async getDeployInfo(): Promise<NWABAPResult | undefined> {
    try {
      let nwabaprc = await readJson('.nwabaprc', { throws: false }) || null;
      if (!nwabaprc) {
        nwabaprc = { abap_package: '', abap_bsp: '', abap_transport: '' }
        const file = readFileSync('./ui5-deploy.yaml', 'utf8')
        const ui5Deploy = parse(file);
        const builderTasks = <any[]>ui5Deploy.builder.customTasks;
        const deployTask = builderTasks.find(task => task.name === 'deploy-to-abap')
        if (deployTask) {
          nwabaprc.abap_package = deployTask.configuration.app.package;
          nwabaprc.abap_bsp = deployTask.configuration.app.name;
          nwabaprc.abap_transport = deployTask.configuration.app.transport;
        }
      }
      return { abap_package: nwabaprc.abap_package, abap_bsp: nwabaprc.abap_bsp, abap_transport: nwabaprc.abap_transport }
    } catch (err) {
      return undefined;
    }
  }

  public async main() {
    let exitCode = 1;
    try {
      const logFile = 'deploy-log.json';
      const gitParams = await this.getGitParams();
      const pkgJson = await this.getPackageInfo();
      const commitInfo = await GitCommitHandler.getGitCommitInfo();
      const deployInfo = await this.getDeployInfo();
      const result = {
        project: pkgJson.name,
        version: pkgJson.version,
        branch: gitParams.branch,
        username: gitParams.username,
        date: DateFormat.formatDate(new Date()),
        time: DateFormat.formatTime(new Date()),
        commit: commitInfo,
        abap_package: deployInfo?.abap_package,
        abap_bsp: deployInfo?.abap_bsp,
        abap_transport: deployInfo?.abap_transport
      }
      await ensureFile(logFile)
      const json = await readJson(logFile, { throws: false }) || []
      const endResult = [result].concat(json);
      await writeJson(logFile, endResult)
      console.log('log entry written to file')
    } catch (ex) {
      console.log(`exception raised: ${ex}`)
    }
    process.exit(exitCode);
  }

}
